apiVersion: v1
kind: Service
metadata:
  name: client-srv
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      # 在 cluster 中的 port
      port: 3000
      # Pod 的 port
      targetPort: 3000