apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  type: NodePort
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      # 在 cluster 中的 port
      port: 4002
      # Pod 的 port
      targetPort: 4002